---
- name: Create ticket for production promotion
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
  - name: Create a change request
    snow_record:
      state: present
      username: "{{ sn_username }}"
      password: "{{ sn_password }}"
      instance: "{{ sn_instance }}"
      data:
        severity: "{{ sn_severity }}"
        priority: "{{ sn_priority }}"
        short_description: "{{ sn_short_description }}"
    register: new_incident

  - debug: 
      var: new_incident.record
