kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: www
  namespace: {{ project_name }}
spec:
  to:
    kind: Service
    name: appserver
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None
