kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/msolberg/polls.git'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"appserver:latest","namespace":"{{ project_name }}"},"fieldPath":"spec.template.spec.containers[?(@.name==\"appserver\")].image","pause":"false"}]
  name: appserver
  namespace: "{{ project_name }}"
  labels:
    app: appserver
    app.kubernetes.io/component: appserver
    app.kubernetes.io/instance: appserver
    app.kubernetes.io/name: appserver
    app.kubernetes.io/part-of: polls
    app.openshift.io/runtime: python
    app.openshift.io/runtime-version: 3.8-ubi7
spec:
  replicas: {{ replica_count }}
  selector:
    matchLabels:
      app: appserver
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: appserver
        deploymentconfig: appserver
    spec:
      containers:
        - resources: {}
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: appserver
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
          terminationMessagePolicy: File
          image: "{{ project_name }}/appserver:latest"
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
