kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/msolberg/polls.git'
  name: appserver
  namespace: {{ project_name }}
  labels:
    app: appserver
    app.kubernetes.io/component: appserver
    app.kubernetes.io/instance: appserver
    app.kubernetes.io/name: appserver
    app.kubernetes.io/part-of: polls
    app.openshift.io/runtime: python
    app.openshift.io/runtime-version: 3.8-ubi7
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'appserver:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'python:3.8-ubi7'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/msolberg/polls.git'
    contextDir: /
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: appserver-generic-webhook-secret
    - type: GitHub
      github:
        secretReference:
          name: appserver-github-webhook-secret
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
  runPolicy: Serial
