kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/msolberg/polls.git'
    openshift.io/generated-by: OpenShiftWebConsole
  name: appserver
  namespace: {{ project_name }}
  labels:
    app: appserver
    app.kubernetes.io/component: appserver
    app.kubernetes.io/instance: appserver
    app.kubernetes.io/name: appserver
    app.kubernetes.io/part-of: polls
    app.openshift.io/runtime: python
    app.openshift.io/runtime-version: 3.8-ubi7
spec:
  lookupPolicy:
    local: false
